const data = {
  products: [
    {
      _id: '1',
      name: 'Paint Splatter',
      category: 'Shirts',
      image: '/images/dan2.jpeg',
      price: 125,
      brand: 'Dan Flashes',
      rating: 3.5,
      numReviews: 5,
      description: 'Complicated Patterned Shirt',
    },
    {
      _id: '2',
      name: 'Pearl Bandana',
      category: 'Shirts',
      image: '/images/dan3.jpeg',
      price: 450,
      brand: 'Dan Flashes',
      rating: 3.5,
      numReviews: 5,
      description: 'Complicated Patterned Shirt',
    },
    {
      _id: '3',
      name: 'Bargain Bin Lollipop',
      category: 'Shirts',
      image: '/images/dan5.jpeg',
      price: 100,
      brand: 'Dan Flashes',
      rating: 2.5,
      numReviews: 5,
      description: 'Complicated Patterned Shirt',
    },
    {
      _id: '3',
      name: 'Gold Tribal from Tribe of Gold',
      category: 'Shirts',
      image: '/images/dan6.jpeg',
      price: 650,
      brand: 'Dan Flashes',
      rating: 3.5,
      numReviews: 5,
      description: 'Complicated Patterned Shirt',
    },
    {
      _id: '4',
      name: 'Whirly Gig',
      category: 'Shirts',
      image: '/images/dan4.jpeg',
      price: 120,
      brand: 'Dan Flashes',
      rating: 3.5,
      numReviews: 5,
      description: 'Complicated Patterned Shirt',
    },
  ],
}
export default data;